#!/bin/bash

charm_file=${KESTREL_DATA_DIR}/charm_hosts

case $1 in

    add)
        # Add the image to the charm++ host's file
        echo "group ${image_name} " >> ${charm_file}
        ;;

    remove)
        # Delete the group and the registered hosts from the charm++ host's file
        sed -ri "
            # Deletes the group of lines between the image_name group and the 
            # next group
            /[[:space:]]*group[[:space:]]+${image_name}([[:space:]]+|$)/ , \
            /[[:space:]]*group/ {

                 # delete the line of group ${image_name}
                 /[[:space:]]*group[[:space:]]+${image_name}([[:space:]]+|$)/d

                 # delete everything except the remaining (next) group
                 /[[:space:]]*group/"\!"d 
            }" ${charm_file}
        ;;

esac
