#!/bin/bash

delete_entry () {
    sed -ri "
        # Deletes the group of lines between the label and the next label
        /^[[:space:]]*Label.*[[:space:]]+${image_name}([[:space:]]+|$)/ , \
        /^[[:space:]]*$|^[[:space:]]*Label/ {

             # delete the line of group ${image_name}
             /^[[:space:]]*Label.*[[:space:]]${image_name}([[:space:]]+|$)/d

             # delete everything except the remaining (next) group
             /^[[:space:]]*Label/"\!"d 
        }" ${TFTPBOOT_DIR}/image-list
}

case $1 in
    add)
        if [ ! -e ${TFTPBOOT_DIR}/image-list ]; then
            echo -e "\ninclude template\n" > ${TFTPBOOT_DIR}/image-list
            chown dnsmasq:kestrel ${TFTPBOOT_DIR}/image-list
        fi
        
        delete_entry
        
        (
            echo "Label KestrelHPC Image : ${image_name}"
            echo "    menu ${image_name}"
            echo "    config ${image_name}"
            echo                            
        ) >> ${TFTPBOOT_DIR}/image-list
        
        chown dnsmasq:kestrel ${TFTPBOOT_DIR}/image-list
        ;;

    remove)
        delete_entry 
        ;;
esac
