#!/bin/bash

# Only continue if a new image is being created
[ "$1" = "add" ] || exit 0

# Since the root is shared with nfs, prevent dhclient-script from calling to
# ifconfig

# Backup original dhclient-script
if [ ! -e /sbin/dhclient-script.bak ]; then
   cp /sbin/dhclient-script /sbin/dhclient-script.bak
fi

sed -r "
# Look for lines containing 'ifconfig'
/^[[:space:]]*ifconfig/{

   # Disable them by adding a '#' at the begining of that line
   s/^/#/g;

:readline

   # if we find a '\' at the end of the line, we will need to disable also the 
   # next one
   /\\\[[:space:]]*$/{
      # Read next line
      N;
      # Comment the line
      s/\n/\n#/g;
      
      # Goto readline
      b readline 
   }
   
   # Add a true statment to avoid breaking any if construct which only contains
   # the disabled ifconfig statement
   a\ true
}" < /sbin/dhclient-script.bak > /sbin/dhclient-script
