#!/bin/bash

# Only continue if a new image is being created
[ "$1" = "add" ] || exit 0

cat <<SETHOSTNAME > /sbin/set_hostname
#!/bin/sh

new_hostname=\$1

# Create a /etc/hosts file
cat > /etc/hosts <<FILE 
127.0.0.1 localhost
127.0.1.1 \${new_hostname}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
FILE

# Set the new hostname
echo "\$new_hostname" > /etc/hostname
hostname "\$new_hostname"

SETHOSTNAME

chmod 755 /sbin/set_hostname
