#!/bin/bash

# This script creates links for supporting software linked to old openmpi 
# libraries

# Only continue if a new image is being created
[ "$1" = "add" ] || exit 0

[ -e /usr/lib/openmpi/lib/libopen-rte.so.0.0.0 ] && \
ln -sf /usr/lib/openmpi/lib/libopen-rte.so.0.0.0 /usr/lib/openmpi/lib/liborte.so.0

[ -e /usr/lib/openmpi/lib/libopen-pal.so.0.0.0 ] && \
ln -sf /usr/lib/openmpi/lib/libopen-pal.so.0.0.0 /usr/lib/openmpi/lib/libopal.so.0

exit 0
