#!/bin/bash

# Only continue if a new image is being created
[ "$1" = "add" ] || exit 0

cat <<- INTERFACES > /etc/network/interfaces
auto lo
iface lo inet loopback
INTERFACES


# Since the root is shared with nfs, prevent dhclient-script from calling to
# ifconfig

# Backup original dhclient-script
if [ ! -e /sbin/dhclient-script.bak ]; then
   cp /sbin/dhclient-script /sbin/dhclient-script.bak
fi

sed -r "
# Look lines containing ifconfig
/^[[:space:]]*ifconfig/{

   # We disable them
   s/^/#/g;

:readline

   # if we found a '\' character at the end, we need also to disable next line
   /\\\[[:space:]]*$/{
      # Read next line
      N;
      # Comment the line
      s/\n/\n#/g;
      
      # Goto readline
      b readline 
   }
   
   # Add a true statment to avoid breaking if structures which only contain one
   # sentence
   a\ true
}" < /sbin/dhclient-script.bak > /sbin/dhclient-script


cat <<-DHCPHOOK > /etc/dhcp3/dhclient-exit-hooks.d/kestrel_dhcp
#!/bin/sh

        echo "\$new_host_name"
        echo "\$old_host_name"

        echo "\$new_host_name"
        echo "\$old_host_name"


case "\$reason" in
    BOUND|RENEW|REBIND|REBOOT)
        
        if [ -n "\$new_host_name" ]; then
            hostname "\$new_host_name"
            echo "\$new_host_name" > /etc/hostname
            
            cat > /etc/hosts <<FILE 
127.0.0.1 localhost
127.0.1.1 \${new_hostname}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
FILE
        fi
        ;;
esac
DHCPHOOK

chmod 755 /etc/dhcp3/dhclient-exit-hooks.d/kestrel_dhcp


cat <<SETHOSTNAME > /sbin/set_hostname
#!/bin/sh

new_hostname=\$1

# Create a /etc/hosts file
cat > /etc/hosts <<FILE 
127.0.0.1 localhost
127.0.1.1 \${new_hostname}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
FILE

# Set the new hostname
echo "\$new_hostname" > /etc/hostname
hostname "\$new_hostname"

SETHOSTNAME

chmod 755 /sbin/set_hostname
