#!/bin/bash

# Only continue if a new image is being created
[ "$1" = "add" ] || exit 0

cat <<- INTERFACES > /etc/network/interfaces
# Used by ifup(8) and ifdown(8). See the interfaces(5) manpage or
# /usr/share/doc/ifupdown/examples for more information.

# The loopback network interface
#auto lo eth0 
auto lo
iface lo inet loopback

#iface eth0 inet dhcp
#        post-up /usr/sbin/ethtool -s $IFACE wol g
#        post-down /usr/sbin/ethtool -s $IFACE wol g

INTERFACES


# Since the root is shared with nfs, prevent dhclient-script from calling to
# ifconfig

# Backup original dhclient-script
if [ ! -e /sbin/dhclient-script.bak ]; then
   cp /sbin/dhclient-script /sbin/dhclient-script.bak
fi

sed -r "
# Look lines containing ifconfig
/^[[:space:]]*ifconfig/{

   # We disable them
   s/^/#/g;

:readline

   # if we found a '\' character at the end, we need also to disable next line
   /\\\[[:space:]]*$/{
      # Read next line
      N;
      # Comment the line
      s/\n/\n#/g;
      
      # Goto readline
      b readline 
   }
   
   # Add a true statment to avoid breaking if structures which only contain one
   # sentence
   a\ true
}" < /sbin/dhclient-script.bak > /sbin/dhclient-script


cat <<-DHCPHOOK > /etc/dhcp3/dhclient-exit-hooks.d/kestrel_dhcp
#!/bin/sh

        echo "\$new_host_name"
        echo "\$old_host_name"

        echo "\$new_host_name"
        echo "\$old_host_name"


case "\$reason" in
    BOUND|RENEW|REBIND|REBOOT)
        
        if [ -n "\$new_host_name" ]; then
            hostname "\$new_host_name"
            echo "\$new_host_name" > /etc/hostname
            
            cat > /etc/hosts <<FILE 
127.0.0.1   localhost \${new_host_name}
#\${new_ip_address} \${new_host_name}
FILE
        fi
        ;;
esac
DHCPHOOK

chmod 755 /etc/dhcp3/dhclient-exit-hooks.d/kestrel_dhcp


cat <<SETHOSTNAME > /sbin/set_hostname
#!/bin/sh

new_hostname=\$1
hostname "\$new_hostname"
echo "\$new_hostname" > /etc/hostname

cat > /etc/hosts <<FILE 
127.0.0.1   localhost \${new_hostname}
#\${new_ip_address} \${new_hostname}
FILE
SETHOSTNAME

chmod 755 /sbin/set_hostname
