#!/bin/bash

cat <<NETWORK > /etc/init.d/kestrel_network
#!/bin/bash
### BEGIN INIT INFO
# Provides:          kestrel_network
# Required-Start:    
# Required-Stop:     
# Default-Start:     S
# Default-Stop:      0 1 6
# Short-Description: Kestrel Network
# Description:       Kestrel Network
### END INIT INFO

case "\$1" in
  start)
      dhclient
      
      for net in /sys/class/net/*; do 
          iface="\${net##*/}"
          ethtool -s "\${iface}" wol g
      done
      ;;
  stop)
      ;;
esac
NETWORK

(
    chmod 755 /etc/init.d/kestrel_network
    update-rc.d -f kestrel_network remove
    update-rc.d kestrel_network start 10 S . stop 50 0 1 6 .
) &>/dev/null

