#!/bin/bash

# SecuringNFS. http://wiki.debian.org/SecuringNFS
if [[ "${secure_nfs}" == "yes" ]]; then

    # Remove nfs related lines
    grep -v "nfs" ${FILE} > ${FILE}.bak

    # Append
    cat <<EOF > ${FILE}.bak
rpc.nfsd        2049/tcp                        # RPC nfsd
rpc.nfsd        2049/udp                        # RPC nfsd
rpc.nfs-cb      32764/tcp                       # RPC nfs callback
rpc.nfs-cb      32764/udp                       # RPC nfs callback
rpc.statd-bc    32765/tcp                       # RPC statd broadcast
rpc.statd-bc    32765/udp                       # RPC statd broadcast
rpc.statd       32766/tcp                       # RPC statd listen
rpc.statd       32766/udp                       # RPC statd listen
rpc.mountd      32767/tcp                       # RPC mountd
rpc.mountd      32767/udp                       # RPC mountd
rpc.lockd       32768/tcp                       # RPC lockd/nlockmgr
rpc.lockd       32768/udp                       # RPC lockd/nlockmgr
rpc.quotad      32769/tcp                       # RPC quotad
rpc.quotad      32769/udp                       # RPC quotad
EOF

   # move the file back
   mv ${FILE}.bak ${FILE}

fi
