#!/bin/sh

case "\$reason" in
    BOUND|RENEW|REBIND|REBOOT)
        
        if [ -n "\$new_host_name" ]; then
            
            echo "\$new_host_name" > /etc/hostname
            hostname "\$new_host_name"
            
            sed -ri "s/127.0.1.1\s.*/127.0.1.1 \${new_host_name}/" /etc/hosts
        fi
        ;;
esac
