#!/bin/bash

if grep -Eq "Host\s+${KESTREL_HOSTNAME}-\*" ${FILE}; then

    sed -ri "
    # Modify the lines between the old kestrel entry and 
    # the next host entry or the next paragraph
    /^\s*[Hh]ost\s+${KESTREL_HOSTNAME}-\*/ , \
    /^\s*[Hh]ost\s+.*|^\s*$/ {
        
        # delete the line which contains Host kestrel-*
        /^\s*[Hh]ost\s+${KESTREL_HOSTNAME}-\*/d

        # delete everything in the selection except the remaining Host entry
        /^\s*[Hh]ost\s+.*/"\!"d 
    }" ${FILE}

fi

# Get the number of the line of the first Host entry
num=$(grep -E -m1 -n "^\s*[Hh]ost\s+" ${FILE})
num=${num%%:*}

# If there is not Host entry then include kestrel entries at the end of the file
if [ -z "${num}" ]; then
    cat <<EOF >> ${FILE}
Host ${KESTREL_HOSTNAME}-*
    StrictHostKeyChecking yes
    HashKnownHosts no
    IdentityFile ~/.ssh/kestrel_id_dsa
EOF

else
    # Add kestrel Host entry before the first Host entry
    sed -ri "${num} i\
Host ${KESTREL_HOSTNAME}-*\n\
    StrictHostKeyChecking yes\n\
    HashKnownHosts no\n\
    IdentityFile ~/.ssh/kestrel_id_dsa\n" ${FILE}
fi

