#!/bin/bash

# Ensure idmapd and stad daemon are enabled and running
########################################################

set_key_value "NEED_STATD"  "yes" ${FILE}
set_key_value "NEED_IDMAPD" "yes" ${FILE}
