#!/bin/bash

# Copyright (C) 2010 Jon Ander Hernández
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


[ -z   "$KESTREL_SHARE" ] && KESTREL_SHARE=/usr/share/kestrel
[ ! -d "$KESTREL_SHARE" ] && KESTREL_SHARE="${0%/*}/share"

# load kestrel_lib
. "$KESTREL_SHARE"/kestrel-lib

add_to_images(){
    local kestrel_user=$1

    msg "Please wait while the user is added to the images"
    
    log=/tmp/${0##*/}-$$.log
    touch ${log}

    # add the user to each image
    for image in $(list_images); do
        image_dir=${KESTREL_IMAGE_DIR}/${image}

        # Add group
        ############

        kestrel_user_gid=$(id -g ${kestrel_user})
        kestrel_user_group_name=$(id -gn ${kestrel_user})

        (
            export LANG=C
            chroot ${image_dir} groupadd  --gid ${kestrel_user_gid} \
                                          ${kestrel_user_group_name} 
        ) &> ${log}

        # Only show the output if something went wrong and it wasn't because 
        # the group was already present
        (( $? != 0 && $? != 9 )) && cat ${log}

        # Add user
        ###########
        kestrel_user_uid=$(id -u ${kestrel_user})
        kestrel_user_gid=$(id -g ${kestrel_user})
        kestrel_user_groups=$(id -Gn ${kestrel_user})

        (
            export LANG=C
            chroot ${image_dir} useradd --uid ${kestrel_user_uid} \
                                        --gid ${kestrel_user_gid} \
                                        --shell "/bin/bash" \
                                        --no-create-home \
                                        ${kestrel_user} 
        ) &> ${log}

        # Only show the output if something went wrong and it wasn't because 
        # the user was already present
        (( $? != 0 && $? != 9 )) && cat ${log}

        for group in ${kestrel_user_groups}; do
            chroot ${image_dir} usermod -a -G ${group} ${kestrel_user}
        done &>/dev/null
    done

    # Create ssh keys
    user_sshkeygen ${kestrel_user}
    
    rm ${log}
}


_add() {
    local user=$1

    # Create the user if it doesn't exist
    if ! id ${user} &>/dev/null; then
        
        if [ -z "${quiet}" ]; then
            question_yN "The user \"${user}\" doesn't exist, Do you want to create it?"
            adduser ${user} ${NEW_USER_OPTIONS}
        else
            if [ -z "${password}" ]; then
                msg -n "Enter new UNIX password: "
                read password
            fi &&
            useradd -m -s /bin/bash ${user} &&
            echo "${user}:${password}" | chpasswd
        fi
    
    fi &&
    adduser ${user} ${KESTREL_GROUP} &&
    add_to_images ${user}
}


_delete() {
    local new_user=$1
    
    # add the user to each image
    for image in $(list_images); do
        image_dir=${KESTREL_IMAGE_DIR}/${image}
        (
            export LANG=C
            chroot ${image_dir} deluser ${new_user}
        ) &> /dev/null
    
    done
    
    deluser ${new_user} ${KESTREL_GROUP}
}

_remove() {
    _delete $1
}


usage() {
echo "
Usage: ${0##*/} options

OPTIONS:

   --list
     List Cluster's users
  
   --add <user>
     Adds a user to the system and to the Cluster
   
   --delete user
     Deletes a user
   
   --quiet
"
}

for param in "$@"; do
    case $param in
        --quiet)
            quiet="yes"
            ;;
        --version|-v)
            kestrel_version
            ;;
        --help|-h)
            usage
            ;;
     esac
done


# If no parameter is specified
(( $# == 0 )) && usage-error


while (( $# > 0 )); do
    case ${1} in
        --list)
            list_users
            ;;

        --add|--delete|--remove)
            (( $# >= 2 )) || usage-error

            # Ensure this script is executed as root
            check_root

            # Call the corresponding function: _add, _add-to-cluster, _delete
            _${1#--} "$2"
            
            shift
            ;;

        --password)
            if [[ -n "${2}" && ! "${2}" =~ ^--.+$ ]]; then
               password="${2}"
               shift 1
            else
               password=""
            fi
            ;;

        --quiet)
            ;;

        --version|-v)
            kestrel_version
            ;;

        --help|-h)
            usage
            ;;

        *)
            usage-error
            ;;
    esac
    shift
done

:
