#!/bin/bash

# Copyright (C) 2010 Jon Ander Hernández
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


[ -z   "$KESTREL_SHARE" ] && KESTREL_SHARE=/usr/share/kestrel
[ ! -d "$KESTREL_SHARE" ] && KESTREL_SHARE="${0%/*}/share"

# load kestrel_lib
. "$KESTREL_SHARE"/kestrel-lib

add_to_images(){
    local kestrel_user=$1

    log=/tmp/${0##*/}-$$.log
    touch ${log}

    # add the user to each image
    for image in $(list_images); do
        image_dir=${KESTREL_IMAGE_DIR}/${image}

        # Add group
        ############

        kestrel_user_gid=$(id -g ${kestrel_user})
        kestrel_user_group_name=$(id -gn ${kestrel_user})

        (
            export LANG=C
            chroot ${image_dir} groupadd  --gid ${kestrel_user_gid} \
                                          ${kestrel_user_group_name} 
        ) &> ${log}

        # Only show the output if something went wrong and it wasn't because 
        # the group was already present
        (( $? != 0 && $? != 9 )) && cat ${log}

        # Add user
        ###########
        kestrel_user_uid=$(id -u ${kestrel_user})
        kestrel_user_gid=$(id -g ${kestrel_user})
        kestrel_user_groups=$(id -Gn ${kestrel_user})

        (
            export LANG=C
            chroot ${image_dir} useradd --uid ${kestrel_user_uid} \
                                        --gid ${kestrel_user_gid} \
                                        --shell "/bin/bash" \
                                        --no-create-home \
                                        ${kestrel_user} 
        ) &> ${log}

        # Only show the output if something went wrong and it wasn't because 
        # the user was already present
        (( $? != 0 && $? != 9 )) && cat ${log}

        for group in ${kestrel_user_groups}; do
            chroot ${image_dir} usermod -a -G ${group} ${kestrel_user}
        done &>/dev/null
    done

    # Create ssh keys
    user_sshkeygen ${kestrel_user}
    
    rm ${log}
}


_add() {
    local new_user=$1

    # add the user to the frontend
    adduser ${new_user} ${NEW_USER_OPTIONS} &&
    adduser ${new_user} ${KESTREL_GROUP}

    # add the user to the images
    add_to_images ${new_user}
}


_add-to-cluster() {
    local user=$1
    
    # check if the user exists.
    if ! id ${user} &>/dev/null; then
        echo "The user \"${user}\" doesn't exist on the system"
    else
        # add the user to the frontend
        adduser ${user} ${KESTREL_GROUP}

        # add the user to the images
        add_to_images ${user}
    fi
}


_delete() {
    local new_user=$1
    
    # add the user to each image
    for image in $(list_images); do
        image_dir=${KESTREL_IMAGE_DIR}/${image}
        (
            export LANG=C
            chroot ${image_dir} deluser ${new_user}
        ) &> /dev/null
    
    done
    
    deluser ${new_user} ${KESTREL_GROUP}
}


usage() {
echo "
Usage: ${0##*/} options

OPTIONS:

   --list
     List Cluster's users
  
   --add user
     Adds a new user to the system and to the Cluster

   --add-to-cluster user
     Adds an existing user to the Cluster

   --delete user
     Deletes a user

"
}

# If no parameter is specified
(( $# == 0 )) && usage-error


while (( $# > 0 )); do
    case ${1} in
        --list)
            list_users
            ;;

        --add|--add-to-cluster|--delete)
            (( $# >= 2 )) || usage-error

            # Ensure this script is executed as root
            check_root

            # Call the corresponding function: _add, _add-to-cluster, _delete
            _${1#--} "$2"
            
            shift
            ;;

        --version|-v)
            kestrel_version
            ;;

        --help|-h)
            usage
            ;;

        *)
            usage-error
            ;;
    esac
    shift
done


