#!/bin/bash

# Copyright (C) 2010 Jon Ander Hernández
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

dir=$(cd ${0%/*}; pwd)

export KESTREL_SHARE=${dir}/share

# load kestrel_lib
. "$KESTREL_SHARE"/kestrel-lib

# Replace $KESTREL_SHARE's default value
export KESTREL_SHARE=${dir}/share

usage() {
echo "
Usage: ${0##*/} options

OPTIONS:

   --web <user>
     Upgrade the web page

   --build
     Create man files with help2man

   --tarball
     Create debian source tarball

   --deb
     Create debian package

   --launchpad
     Upload packages to launchpad
     
   --launchpad-snapshot
     Upload snapshot packages to launchpad
     
   --install
     Install the created package

"
    exit 1
}

clean(){
    ${dir}/debian/rules clean
    rm ${dir}/kestrelhpc*.tar.gz* 2> /dev/null
    rm ${dir}/*.dsc 2> /dev/null
    rm ${dir}/../kestrelhpc*{.upload,.deb,.build,.dsc,.changes,.tar.gz} 2> /dev/null
    rm ${dir}/debian/*.manpages 2> /dev/null
    rm ${dir}/*.8 2> /dev/null
}

check_install_files(){
    pushd ${dir} &> /dev/null
    non_installed_files=0
    find share -type f | grep -v "\/\." | while read file; do
       installed=""
       for inst in debian/*.install; do
           grep -q "${file}" "${inst}" && installed=${inst}
       done
       if [ -z "${installed}" ]; then
           non_installed_files=$(( $non_installed_files + 1 ))
           echo "file ${file} not installed"
       #else
       #    echo "file ${file} installed on ${inst}"
       fi
    done
    #echo "Total of non installed files : ${non_installed_files}"
    popd &> /dev/null
}

build(){
    clean
    # create man files
    pushd ${dir} &> /dev/null
    for i in *; do
        [ ! -f ${i} -o ! -x ${i} ] && continue
        for install in debian/*.install; do
            if grep -q "${i}" "${install}"; then
                help2man "./${i}" --section=8 --no-info --output="${i}.8"
                echo "${i}.8" >> ${install%%.install}.manpages
            fi
        done
    done
    popd &> /dev/null
}


for param in $@; do
   [[ ${param} == "--install" ]] && m_install=true;
done


# If no parameter is specified
(( $# == 0 )) && usage-error


case ${1} in
    --install)
        ;;
        
    --web)
        user=${2}
        dir=${0}/../Web/
        rsync -avP --delete --exclude .svn -e ssh ${dir} ${2},kestrelhpc@frs.sourceforge.net:htdocs
        exit 0
        ;;
        
    --build)
        build
        exit 0
        ;;
        
    --tarball)
        build
        dpkg-source -I.svn '-i^\.svn/' -b .
        exit 0
        ;;
        
    --deb)
        build &&
        debuild -I.svn '-i^\.svn/' -us -uc -b &&
        [ "${m_install}" == "true" ] && sudo dpkg -i ../*.deb &&
        exit 0
        ;;
        
    --launchpad)
        exit 0
        ;;
        
    --launchpad-snapshot)
        build
        . share/kestrel-lib
        release=${KESTREL_VERSION}.$(date +%Y.%m.%d)
        dch -b -v ${release} &&
        release=$(sed -rn 's/^kestrelhpc \((.*)\).*$/\1/p' $dir/debian/changelog | head -1) &&
        debuild -S -I.svn '-i^\.svn/' &&
        dput ppa:kestrel/kestrelhpc ../kestrelhpc_${release}_source.changes &&
        [ "${m_install}" == "true" ] && sudo dpkg -i ../*.deb &&
        exit 0
        ;;

    --unstable-snapshot)
        build
        . share/kestrel-lib
        release=${KESTREL_VERSION}.$(date +%Y.%m.%d)
        dch -b -v ${release} &&
        release=$(sed -rn 's/^kestrelhpc \((.*)\).*$/\1/p' $dir/debian/changelog | head -1) &&
        debuild -S -I.svn '-i^\.svn/' &&
        dput ppa:kestrel/unstable ../kestrelhpc_${release}_source.changes &&
        [ "${m_install}" == "true" ] && sudo dpkg -i ../*.deb &&
        exit 0
        ;;
        
    --clean)
        clean
        exit 0
        ;;
     
    --check-install-files)
        check_install_files
        exit 0
        ;;

    --version|-v)
        kestrel_version
        ;;
        
    *)
        usage-error
        ;;
esac
