#!/bin/sh

new_hostname=\$1
FRONTEND_IP=\${2:-192.168.30.1}
FRONTEND=\$3

# Create a /etc/hosts file
cat > /etc/hosts <<FILE 
127.0.0.1 localhost
127.0.1.1 \${new_hostname}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

\${FRONTEND_IP} \${FRONTEND} frontend
FILE

# Set the new hostname
echo "\$new_hostname" > /etc/hostname
hostname "\$new_hostname"
