#!/bin/bash

case $1 in
    add)
        # The fstab and the export entries will be created during the 
        # configuration stage
        continue
        ;;

    remove)
        # umount the image
        umount ${NFS4_ROOT}/kestrel/${image_name}/lib/modules
        umount ${NFS4_ROOT}/kestrel/${image_name}

        # Delete from the fstab
        sed -ri "/[^#]*\/kestrel\/${image_name}/d" ${FILE}
        ;;
esac
