#!/bin/bash

# Check if the mac is defined
if [[ -n "${mac}" ]]; then
    
    pxemac=$(mac_2_pxemac ${mac})
    
    case ${action} in
        disconnect|desregister)
           if [[ -n "${pxemac}" && "$reboot" = "False" && 
                 -e ${TFTPBOOT_DIR}/pxelinux.cfg/${pxemac} ]]; then
              rm ${TFTPBOOT_DIR}/pxelinux.cfg/${pxemac}
           fi
           ;;

        wake|reboot)
            cp -f ${TFTPBOOT_DIR}/pxelinux-${image_name} \
                  ${TFTPBOOT_DIR}/pxelinux.cfg/${pxemac}
            ;;

        shutdow)
            if [[ -e ${TFTPBOOT_DIR}/pxelinux.cfg/${pxemac} ]]; then
               rm ${TFTPBOOT_DIR}/pxelinux.cfg/${pxemac}
            fi
            ;;
    esac
    
else
    
    case ${action} in
        start-register)
            # Set the pxelinux register configuration as the default
            sed "/append/s/$/ register=${group} /" \
                < ${TFTPBOOT_DIR}/pxelinux-${image_name}    \
                > ${TFTPBOOT_DIR}/pxelinux.cfg/default
            ;;
            
        stop-register)
            # Reboot by default
            cp -f ${TFTPBOOT_DIR}/pxelinux-reboot ${TFTPBOOT_DIR}/pxelinux.cfg/default
            ;;
    esac
    
fi
