#!/bin/bash

# Check if the hostname is defined and is a valid hostname
if [[ "${hostname}" =~ ^${hostname_re}$ ]]; then

case ${action} in
    connect|register)
       sed -ri "//^[^#]*\s+${hostname}([^0-9]|$)/d
                
                /group ${image}$/ a\    host ${hostname} ++cpus ${cpus}
                
                /group ${group}$/ a\    host ${hostname} ++cpus ${cpus}
                
                /group main/ a\    host ${hostname} ++cpus ${cpus}
               " ${CHARM_HOSTFILE}
       ;;
    disconnect|desregister)
       # Remove any old entry related to this node
       sed -ri "/^[^#]*\s+${hostname}([^0-9]|$)/d" ${CHARM_HOSTFILE}
       ;;
esac

fi
