#!/bin/bash

# Check if the hostname is defined and is a valid hostname
if [[ "${hostname}" =~ ^${hostname_re}$ ]]; then

case ${action} in
    connect|register)
       
       # Remove any old entry related to this node
       sed -ri "/^[^#]*\s+${hostname}([^0-9]|$)/d" ${OPENMPI_HOSTFILE}
       
       # Add new entries
       echo "${hostname} slots=${cpus:-1} " >> ${OPENMPI_HOSTFILE}
       ;;

    disconnect|desregister)
    
       # Remove any old entry related to this node
       sed -ri "/^[^#]*\s+${hostname}([^0-9]|$)/d" ${OPENMPI_HOSTFILE}
       ;;
esac

fi
