#!/bin/bash

# Check if the hostname is defined and is a valid hostname
if [[ "${hostname}" =~ ^${hostname_re}$ ]]; then

OPENMPI_GROUPFILE=$(eval_variables ${OPENMPI_GROUPFILE})

delete_entries() {
    # Remove any old entry related to this node
    sed -ri "/^\s*${hostname}([^0-9]|$)/d" ${OPENMPI_HOSTFILE}

    [ -e $OPENMPI_GROUPFILE ] &&
    sed -ri "/^\s*${hostname}([^0-9]|$)/d" ${OPENMPI_GROUPFILE}
}

case ${action} in
    connect|register)

       delete_entries
       
       # Add new entries
       echo "${hostname} slots=${cpus:-1} " >> ${OPENMPI_HOSTFILE}

       echo "${hostname} slots=${cpus:-1} " >> ${OPENMPI_GROUPFILE}
       ;;

    disconnect|desregister)

       delete_entries
       ;;
esac

fi
