#!/bin/bash

# Check if the mac is defined
if [ -n "${mac}" ]; then

case ${action} in
    disconnect|desregister)
       pxemac=$(mac_2_pxemac ${mac})
       [[ -n "${pxemac}" && "$reboot" = "False" ]] &&
       rm ${TFTPBOOT_DIR}/pxelinux.cfg/${pxemac} 2>/dev/null
       ;;

    wake|reboot)
        cp -f ${TFTPBOOT_DIR}/${image_name} \
              ${TFTPBOOT_DIR}/pxelinux.cfg/${pxemac}
        #chown dnsmasq:${KESTREL_GROUP} ${TFTPBOOT_DIR}/pxelinux.cfg/${pxemac}
        ;;

    shutdow)
        rm ${TFTPBOOT_DIR}/pxelinux.cfg/${pxemac} 2>/dev/null
        ;;

esac

fi
