#!/bin/bash

if [[ "${action}" == @(halt|reboot) ]]; then
    
    unset SSH_AUTH_SOCK
    
    # FIXME Hack to avoid something I don't remember now
    su kestrel -c "ssh ${host} sudo ${op}" 2> /dev/null || {
    warn "\tUnable to ${op} ${host} (ip:${ip})"; fail=True; } &
    
    wait $!
    
    if [ -n "${fail}" ]; then
        return 1
    fi
fi
