#!/bin/bash

configure_range_ip() {
    local result
    local title="Configure the Frontend's DHCP server"
    local msg=( "Insert the ip range for the dhcp server" )
    
    result="${DHCP_STARTING_IP} - ${DHCP_ENDING_IP}"
    
    result=$( kestrel_dialog inputbox "${title}" msg[@] "${result}")
    
    msg=( "Insert the ip range for the dhcp server" 
          ""
          "Invalid ip range!")
    
    while [[ "$?" == "0" ]] &&
          [[ ! "${result}" =~ ^(${ip_re})[\ \t]*-[\ \t]*(${ip_re})$ ]]; do
        result=$( kestrel_dialog inputbox "${title}" msg[@] "${result}" )
    done
    
    export DHCP_STARTING_IP=${BASH_REMATCH[1]}
    export   DHCP_ENDING_IP=${BASH_REMATCH[2]}
    
    echo "DHCP_STARTING_IP=\"${DHCP_STARTING_IP}\""
    echo   "DHCP_ENDING_IP=\"${DHCP_ENDING_IP}\""
    
#    set_key_value "DHCP_STARTING_IP" "${DHCP_STARTING_IP}" "${FILE}"
#    set_key_value   "DHCP_ENDING_IP"   "${DHCP_ENDING_IP}" "${FILE}"
}

configure_range_ip

