#!/bin/bash

case $1 in
    install)
        # The fstab and the export entries will be created during the 
        # configuration stage
        continue
        ;;

    remove)
        # Delete from the exports
        sed -ri "/[^#]*\/kestrel\/${image_name}/d" /etc/exports
        ;;
esac
