#!/bin/bash

case $1 in
    install)
        # The fstab and the export entries will be created during the 
        # configuration stage
        continue
        ;;

    uninstall)
        # umount the image
        echo "umount \"${NFS4_ROOT}/kestrel/${image_name}/lib/modules\""
        echo "umount \"${NFS4_ROOT}/kestrel/${image_name}\""
        
        umount ${NFS4_ROOT}/kestrel/${image_name}/lib/modules
        umount ${NFS4_ROOT}/kestrel/${image_name}

        # Delete from the fstab
        sed -ri "/[^#]*\/kestrel\/${image_name}/d" /etc/fstab
        ;;
esac
