#!/bin/bash

case $1 in
    install)
        # The fstab and the export entries will be created during the 
        # configuration stage
        continue
        ;;

    uninstall)
        mount_dir=$(mount | sed -rn \
                    "s/.*\s([^\ \t]*\/kestrel\/${image_name})\s+.*/\1/p")
        
        # umount the image
        echo "umount \"${mount_dir}/lib/modules\""
        umount ${mount_dir}/lib/modules
        
        echo "umount \"${mount_dir}\""
        umount ${mount_dir}
        
        # Delete from the fstab
        sed -ri "/[^#]*\/kestrel\/${image_name}/d" /etc/fstab
        ;;
esac
