#! /bin/sh

set -e

# Don't bother to restart sshd when lo is configured.
[ "$IFACE" = lo ] && exit 0

# Only run from ifup.
[ "$MODE" != start ] && exit 0

[ -e /usr/share/kestrel/default.conf ] &&
. /usr/share/kestrel/default.conf

[ -e /etc/kestrel/kestrel.conf ] &&
. /etc/kestrel/kestrel.conf

if ifconfig $IFACE | grep -Eq "[^0-9]${FRONTEND_IP}[^0-9]"; then

    # idmapd sometimes fails to start on Ubuntu
    if [ -e /etc/init/idmapd.conf ]; then
        initctl status idmapd || initctl start idmapd
    fi

    [ -x /etc/init.d/dnsmasq ] &&
        invoke-rc.d dnsmasq restart

    [ -x /etc/init.d/kestrel_daemon ] &&
    invoke-rc.d kestrel_daemon restart

fi
