#!/bin/bash

delete_entry () {
    sed -ri "
        # Deletes the group of lines between the label and the next label
        /^\s*Label.*\s+${image_name}(\s+|$)/ , \
        /^\s*$|^\s*Label/ {

             # delete the line of group ${image_name}
             /^\s*Label.*\s+${image_name}(\s+|$)/d

             # delete everything except the remaining (next) group
             /^\s*Label/"\!"d 
        }" ${FILE}
}

case $1 in
    install)
        if (($(stat -c %s ${FILE}) == 0)); then
            echo -e "\ninclude template\n" > ${FILE}
        fi
        
        delete_entry
        
        cat <<EOF >> ${FILE}
Label KestrelHPC Image : ${image_name}
    menu ${image_name}
    config ${image_name}

EOF
        
        ;;

    remove)
        delete_entry 
        ;;
esac
