#!/bin/bash

# Ensure idmapd and stad daemon are enabled
#############################################

set_key_value "NEED_STATD"  "yes" ${FILE}
set_key_value "NEED_IDMAPD" "yes" ${FILE}

# SecuringNFS. http://wiki.debian.org/SecuringNFS
if [[ "${secure_nfs}" == "yes" ]]; then
    set_key_value "STATDOPTS" "\"--port 32765 --outgoing-port 32766\"" ${FILE}
fi
