#!/bin/bash

if grep -Eq "Host[[:space:]]+${KESTREL_HOSTNAME}-\*" ${FILE}; then

    # Deletes the old kestrel_hostname entry. Deletes everything between the old
    # Host kestrel-* entry and the next Host entry
    sed -ri "
    /^[[:space:]]*[Hh]ost[[:space:]]+${KESTREL_HOSTNAME}-\*/ , \
    /^[[:space:]]*[Hh]ost[[:space:]]+.*|^[[:space:]]*$/ {
        
        # delete the line of Host kestrel-*
        /^[[:space:]]*[Hh]ost[[:space:]]+${KESTREL_HOSTNAME}-\*/d

        # delete everything except the remaining (next) Host
        /^[[:space:]]*[Hh]ost[[:space:]]+.*/"\!"d 
    }" ${FILE}

fi

# Get the number of the line of the first Host entry
num=$(grep -E -m1 -n "^[[:space:]]*[Hh]ost[[:space:]]+" ${FILE})
num=${num%%:*}

# If there is not Host entry then include kestrel entries at the end of the file
if [ -z "${num}" ]; then
    (
    echo
    echo "Host ${KESTREL_HOSTNAME}-*"
    echo "    StrictHostKeyChecking yes"
    echo "    HashKnownHosts no"
    echo "    IdentityFile ~/.ssh/kestrel_id_dsa
    ) >> ${FILE}

else
    # Add kestrel Host entry before the first Host entry
    sed -ri "${num} i\
Host ${KESTREL_HOSTNAME}-*\n\
    StrictHostKeyChecking yes\n\
    HashKnownHosts no\n\
    IdentityFile ~/.ssh/kestrel_id_dsa\n" ${FILE}
fi

