#!/bin/bash

# udev rule which econfigures the drivers and creates a xorg.conf if a Nvidia
# hardware is detected.

# Ubuntu selects the OpenGL stack setting the loader
update-alternatives --list gl_conf &> /dev/null &&
update-alternatives --set gl_conf /usr/lib/nvidia-current/ld.so.conf 

# Debian 
nvidia_diversion=/usr/lib/nvidia
for file in libGL.so.1 libGL.so libglx.so; do

   update-alternatives --list \${file} &> /dev/null &&
   update-alternatives --set \${file} \${nvidia_diversions}/\${file}

done

cat <<EOF > /etc/X11/xorg.conf
Section "Monitor"
   Identifier     "Monitor0"
   VendorName     "Unknown"
   ModelName      "Unknown"
   HorizSync       28.0 - 33.0
   VertRefresh     43.0 - 72.0
   Option         "DPMS"
EndSection

Section "Device"
   Identifier     "Device0"
   Driver         "nvidia"
   Option         "NoLogo" "True"
   VendorName     "NVIDIA Corporation"
EndSection

Section "Screen"
   Identifier     "Screen0"
   Device         "Device0"
   Monitor        "Monitor0"
   DefaultDepth    24
   SubSection     "Display"
       Depth       24
   EndSubSection
EndSection
