#!/bin/bash

# Set the exported home (variable $KESTREL_HOME) for each user on the guest os

list_users | while read user; do

   home=/${KESTREL_HOME}/${user}

   sed -ri "/^${user}:/s#^(.*:.*:.*:.*:.*:).*(:.*)#\1/${home}\2#" ${FILE}

done
