#!/bin/bash

# Only continue if a new image is being created
[ "$1" = "add" ] || exit 0

# Ensure idmapd and stad daemon are enabled and running
########################################################

set_variable "NEED_STATD"  "yes" /etc/default/nfs-common
set_variable "NEED_IDMAPD" "yes" /etc/default/nfs-common
