#!/bin/bash

# Copyright (C) 2010, 2011 Jon Ander Hernández
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[ -z "$KESTREL_SHARE" ] && KESTREL_SHARE=/usr/share/kestrel

# Enable extended pattern matching
shopt -s extglob

# load_config
#
#     Loads the config from the config file default.conf, from the defaul.d dir
#     and from the user's 

load_config() {
    
    # Source default config file
    [ -f ${KESTREL_SHARE}/default.conf ] && . ${KESTREL_SHARE}/default.conf

    # Source default config dir
    for configfile in ${KESTREL_SHARE}/default.d/!(internal*); do
        [ -e "$configfile" ] && . "$configfile"
    done

    # Load user's local config
    [ -f ${KESTREL_ETC}/kestrel.conf ] && . ${KESTREL_ETC}/kestrel.conf

    # Source internal variables
    for configfile in ${KESTREL_SHARE}/default.d/internal*; do
        [ -e "$configfile" ] && . "$configfile"
    done
}


# All the functions defined in this library require that the config is loaded
load_config



# variable_list
# 
#     List variables

variable_list() {
    cat ${KESTREL_SHARE}/default.conf \
        ${KESTREL_SHARE}/default.d/* \
        ${KESTREL_ETC}/kestrel.conf 2>/dev/null | \
        sed -nr 's/^[[:space:]]*([A-Za-z0-9_]+)=.*$/\1/p' | \
        sort | uniq
}


# variable_list2
# 
#     List non internal variables

variable_list2() {
    cat ${KESTREL_SHARE}/default.conf \
        ${KESTREL_SHARE}/default.d/!(internal*) \
        ${KESTREL_ETC}/kestrel.conf 2>/dev/null | \
        sed -nr 's/^[[:space:]]*([A-Za-z0-9_]+)=.*$/\1/p' | \
        sort | uniq
}


# variable_values
# 
#     List variables

variable_values() {
    for var in $(variable_list2); do
        echo "${var}=${!var}"
    done
}

# export_config
# 
#     Export config variables. This is useful for executing scripts under a 
#     chroot which require access to kestrel's config.

export_config() {
    for variable in $(variable_list); do
        export $variable
    done
}


# detect_iface
# 
#     Detect the network interface associated to the FRONTEND_IP and export the
#     result as the variable KESTREL_IFACE

detect_iface() {
    unset KESTREL_IFACE
    
    # Check if $FRONTEND_IP contains a valid ip
    [[ ${FRONTEND_IP} =~ ${ip_re} ]] &&
    for net in /sys/class/net/*; do
        ifconfig ${net##*/} 2>/dev/null | grep -Eq "addr:${FRONTEND_IP}\s" &&
            export KESTREL_IFACE=${net##*/} && 
            return 0
    done
}

