#!/bin/bash

# Copyright (C) 2010 Jon Ander Hernández
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[ -z "$KESTREL_SHARE" ] && KESTREL_SHARE=/usr/share/kestrel

# Loads the config from the config file default.conf, from the defaul.d dir
# and from the user's 

load_config() {
    # Source default config file
    [ -f ${KESTREL_SHARE}/default.conf ] && . ${KESTREL_SHARE}/default.conf

    # Source default config dir
    for configfile in ${KESTREL_SHARE}/default.d/*; do
        [ -e "$configfile" ] && . "$configfile"
    done

    # Load user's local config
    [ -f ${KESTREL_ETC}/kestrel.conf ] && . ${KESTREL_ETC}/kestrel.conf
}

# All the functions defined in this library require the config is loaded
load_config


# Export config variables. This is useful for executing scripts under a chroot
# which require access to kestrel's config.

export_config() {
    for variable in \
        $(cat ${KESTREL_SHARE}/default.conf \
              ${KESTREL_SHARE}/default.conf.d/* \
              ${KESTREL_ETC}/kestrel.conf 2>/dev/null | \
              sed -nr 's/^[[:space:]]*([A-Za-z0-9_]+)[[:space:]]*=.*$/\1/p' | \
              sort | uniq)
    do
        export $variable
    done
}
