#!/bin/bash

# set_variable <key> <value> <file> [<separator_re> <separator>]
# 
#     Helps replacing/setting key-values on files

set_variable() {
    local key=$1
    local value=$2
    local file=$3
    local sep=${4:-=}
    local sep2=${5:-$sep}

    [ "$sep" == " " ] && sep="\s"
    [[ -e "${file}" && ! -e "${file}.bak" ]] && cp ${file} ${file}.bak
    
    if [ ! -e ${file} ] || ! grep -qE "^[#\s]*${key}\s*${sep}" ${file}; then
        echo "${key}${sep2}${value}" >> ${file}
    else
        sed -ri "/^[#\s]*${key}\s*${sep}/s|^.*$|${key}${sep2}${value}|" ${file}
    fi
}
