#!/bin/bash

# Since the Nvidia propietary OpenGL drivers are installed which replace the
# free ones, reconfigure them so that the free ones are back as the default 
# ones.

# Ubuntu selects the OpenGL stack setting the loader
update-alternatives --list gl_conf &> /dev/null &&
update-alternatives --set gl_conf /usr/lib/mesa/ld.so.conf 

# Debian 
nvidia_diversion=/usr/lib/nvidia/diversions
for file in libGL.so.1 libGL.so libglx.so; do

   update-alternatives --list ${file} &> /dev/null &&
   update-alternatives --set ${file} ${nvidia_diversion}/${file}

done

