#!/bin/bash

# Copy the kernel and the initramfs to the tftpboot
 
if [ "${NODE_KERNEL}" == "auto" ]; then
    # Check if $(uname -r) kernel exists on the system. If we are installing
    # KestrelHPC using debootstrap the installed kernel may not be present on
    # the installed system.
    if [ -e "/boot/vmlinuz-$(uname -r)" ]; then
        KERNEL_VERSION=$(uname -r)
    
    # If $(uname -r) was not present, look for another kernel
    else
        KERNEL_VERSION=$(ls -1 /boot/vmlinuz-* | tail -n1 | \
                         sed -rn "s#/boot/vmlinuz-(.*)#\1#p")
        warn_config "Current kernel \"$(uname -r)\" not found on the system"
        warn_config "Using \"${KERNEL_VERSION}\" instead"
    fi

else
    if [ ! -e "/boot/vmlinuz-${NODE_KERNEL}" ]; then
        
        KERNEL_VERSION=$(ls -1 /boot/vmlinuz-* | tail -n1 | \
                         sed -rn "s#/boot/vmlinuz-(.*)#\1#p")
        
        warn_config "Kernel \"${NODE_KERNEL}\" not found, please check your kestrel config"
        warn_config "Using \"${KERNEL_VERSION}\" instead"
    else
        KERNEL_VERSION=${NODE_KERNEL}
    fi
fi

if [ -n "${KERNEL_VERSION}" ]; then
    
    [ -e "/boot/vmlinuz-${KERNEL_VERSION}" ] && 
        cp /boot/vmlinuz-${KERNEL_VERSION} ${TFTPBOOT_DIR}/vmlinuz
    
    if [ ! -e "/boot/initramfs-${KERNEL_VERSION}.img" ]; then
        warn_config "/boot/initramfs-${KERNEL_VERSION}.img not found"
        msg_config "Please wait, Dracut will take some time"
        dracut -q --force "/boot/initramfs-${KERNEL_VERSION}.img"
    fi
    
    cp /boot/initramfs-${KERNEL_VERSION}.img ${TFTPBOOT_DIR}/dracut-img ||
    warn_config "Failed copying initramfs! Try configuring again."
    
else
    warn_config "No kernel found on the system"
    
    # Fail
    false
fi

