#!/bin/bash

# Copy the kernel and the initramfs to the tftpboot
 
if [ "${NODE_KERNEL}" == "auto" ]; then
    # Check if $(uname -r) kernel exists on the system. If we are installing
    # KestrelHPC using debootstrap the installed kernel may not be present on
    # the installed system.
    if [ -e "/boot/vmlinuz-$(uname -r)" ]; then
        KERNEL_VERSION=$(uname -r)
    
    # If $(uname -r) was not present, look for another kernel
    else
        KERNEL_VERSION=$(ls -1 /boot/vmlinuz-* | tail -n1 | \
                         sed -rn "s#/boot/vmlinuz-(.*)#\1#p")
        msg "Current kernel \"$(uname -r)\" not found on the system"
        msg "Using \"${KERNEL_VERSION}\" instead"
    fi

else
    if [ ! -e "/boot/vmlinuz-${NODE_KERNEL}" ]; then
        
        KERNEL_VERSION=$(ls -1 /boot/vmlinuz-* | tail -n1 | \
                         sed -rn "s#/boot/vmlinuz-(.*)#\1#p")
        
        msg "Kernel \"${NODE_KERNEL}\" not found, please check your kestrel config"
        msg "Using \"${KERNEL_VERSION}\" instead"
    else
        KERNEL_VERSION=${NODE_KERNEL}
    fi
fi

if [ -n "${KERNEL_VERSION}" ]; then
    
    [ -e "/boot/vmlinuz-${KERNEL_VERSION}" ] && 
        cp /boot/vmlinuz-${KERNEL_VERSION} ${TFTPBOOT_DIR}/vmlinuz
    
    if [ ! -e "/boot/dracut.img-${KERNEL_VERSION}" ]; then
        msg "Please wait, Dracut will take some time"
        dracut-update-initramfs -c -k ${KERNEL_VERSION} |& cat
    fi
    
    [ -e "/boot/dracut.img-${KERNEL_VERSION}" ] &&
        cp /boot/dracut.img-${KERNEL_VERSION} ${TFTPBOOT_DIR}/dracut-img
    
    chown dnsmasq:kestrel ${TFTPBOOT_DIR}/{vmlinuz,dracut-img,initrd.img}

else
    warn_info "No kernel found on the system"
    # Fail
    false
fi

