#!/bin/bash

echo "xserver-xorg xserver-xorg-video-all xserver-xorg-input-all x11-xserver-utils xinit xterm libgl1-mesa-glx libgl1-mesa-dri chromium-opengl-bin chromium-opengl-lib"

case ${OS_DISTRIBUTION}-${OS_RELEASE} in
    Debian-*)
        echo "nvidia-glx"
        ;;
    Ubuntu-*)
        echo "nvidia-current"
        ;;
esac
