#!/bin/bash

# This script creates the pxelinux config file for booting into the configured
# image.

#cp ${TFTPBOOT_DIR}/template ${TFTPBOOT_DIR}/${image_name}
cat <<EOF > ${TFTPBOOT_DIR}/${image_name}
include template

label linux1
  menu label Dracut NFS 3
  kernel vmlinuz
  append initrd=dracut-img root=nfs:${FRONTEND_IP}:${NFS4_ROOT}/kestrel/${image_name} ip=dhcp selinux=0 aufslive ro quiet splash vga=789

label linux0
  menu label Dracut NFS 4
  kernel vmlinuz
  append initrd=dracut-img root=nfs4:${FRONTEND_IP}:/kestrel/${image_name} ip=dhcp selinux=0 aufslive ro quiet splash vga=789

label reboot
  menu label reboot
  kernel reboot.c32

label All KestrelHPC node images
  menu Available kestrel node images
  config image-list

#label memtest
#  menu label Memory Test
#  kernel memtest

label local
  menu label Boot from local drive
  localboot 0

label linux0
  menu label Dracut NFS4 DEBUG
  kernel vmlinuz
  append initrd=dracut-img root=nfs4:${FRONTEND_IP}:/kestrel/${image_name} ip=dhcp selinux=0 aufslive ro rdshell rdnetdebug rdinfo plymouth:debug

EOF

chown dnsmasq:kestrel ${TFTPBOOT_DIR}/${image_name}
